server:
  host: 0.0.0.0
  port: 8080

database:
  url: http://localhost:8529
  database: stag
  username: root
  # password: set via STAG_DATABASE_PASSWORD or ARANGO_PASSWORD env var

log_level: info

metrics:
  enabled: true
  path: /metrics